### ISSUE TITLE
[feat] Unsplash API Integration

### ISSUE THREAD

**Issue by beradeep** [beradeep/CollegeSearch#1]
### Unsplash/Any image library Integration

> _Refactor the current image catalogue in the home page and integrate Unsplash or any other image library API to display images of colleges/universities._

**Comment by JonibekXolmonov** [comment]
Hi, images of universities/colleges must be from Indian universities/colleges or any Universities/colleges!

**Comment by beradeep** [comment]
@JonibekXolmonov Since it's a catalogue on the home page, any university/college images will do

**Comment by JonibekXolmonov** [comment]
I try to solve this one,sir!

**Comment by beradeep** [comment]
Sure, go for it!

**Comment by JonibekXolmonov** [comment]
Hi sir, I solved but no access

 Permission to beradeep/CollegeSearch.git denied to JonibekXolmonov. unable to access 'https://github.com/beradeep/CollegeSearch.git/': The requested URL returned error: 403

**Comment by JonibekXolmonov** [comment]
due to impossibility from extra branch, I created fork.Please review it

**Comment by beradeep** [comment]
Hi, raise a pull request if you have done it.

**Comment by JonibekXolmonov** [comment]
remote: Permission to beradeep/CollegeSearch.git denied to JonibekXolmonov.
fatal: unable to access 'https://github.com/beradeep/CollegeSearch.git/': The requested URL returned error: 403
I am getting this error, I think you should grant some kind of permission? or I'm doing something wrong?

**Comment by beradeep** [comment]
Hi, I think you are directly attempting to push to this repository. You need to first create a fork of it, push the changes there and then raise a pull request to this repository.

**Comment by JonibekXolmonov** [comment]
I created, have a look

**Comment by JonibekXolmonov** [comment]
you can change Unsplash client id in Constants file

**Comment by beradeep** [comment]
> you can change Unsplash client id in Constants file

Don't worry I have changed it
